export const REQUEST_USER_SIGN = 'REQUEST_USER_SIGN';
export const SUCCESS_USER_SIGN = 'SUCCESS_USER_SIGN';
export const INVALID_USER_SIGN = 'INVALID_USER_SIGN';
export const VALID_USER_SIGN = 'VALID_USER_SIGN';
